version = "3.7.17"
runner.dialect = scala3

# 基本設定
maxColumn = 100
encoding = "UTF-8"
docstrings.style = Asterisk

# インデント
indent.main = 2
indent.defnSite = 2

# 改行
newlines.beforeMultiline = keep
newlines.alwaysBeforeElseAfterCurlyIf = false

# スペース
spaces.inImportCurlyBraces = true

# 並び替え
rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers,
  PreferCurlyFors
]

# Scala 3 の構文
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = true
