site_name: ゲーム開発のケーススタディ
site_description: Documentation for the Game Development project.
site_author: Project Team
repo_url: https://github.com/k2works/case-study-game-dev
repo_name: case-study-game-dev

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

extra_css:
  - docs/mkdocs/assets/css/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: plantuml
          class: plantuml
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
      permalink: true
  - plantuml_markdown:
      server: !!python/object/apply:os.getenv
        - PLANTUML_SERVER_URL
        - http://www.plantuml.com/plantuml
      format: svg

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - docs/assets/js/extra.js

extra:
  plantuml_url: http://www.plantuml.com/plantuml
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/k2works/ai-programming-exercise
      name: GitHub Repository

plugins:
  - search

nav:
  - Home: index.md
  - 要件:
    - 要件: ./requirements/要件.md
  - 開発:
    - 開発計画: ./development/開発計画.md
    - ユーザーインターフェース設計: ./requirements/ユーザーインターフェース設計.md
    - アーキテクチャ設計: ./requirements/アーキテクチャ設計.md
    - データモデル設計: ./requirements/データモデル設計.md
    - ドメインモデル設計: ./requirements/ドメインモデル設計.md
  - 運用:
    - セットアップ: ./operation/セットアップ.md
    - MkDocs GitHub Actions設定: ./operation/MkDocs_GitHub_Actions設定.md
  - ADR:
      - 概要: ./adr/index.md
      - TypeScriptの採用: ./adr/0001-adopt-typescript.md
      - Vitestの採用: ./adr/0002-adopt-vitest.md
      - Canvas APIの採用: ./adr/0003-adopt-canvas-api.md
      - TDDアプローチの採用: ./adr/0004-adopt-tdd-approach.md
      - GitHub Actionsの採用: ./adr/0005-adopt-github-actions.md
      - Vercelの採用: ./adr/0006-adopt-vercel.md
  - 日誌:
    - 2025年7月31日: ./journal/20250731.md
    - 2025年8月2日: ./journal/20250802.md
  - 参考資料:
    - Case1: ./reference/case-1/index.md
