site_name: ゲーム開発のケーススタディ
site_description: Documentation for the Game Development project.
site_author: Project Team
repo_url: https://github.com/k2works/case-study-game-dev
repo_name: case-study-game-dev

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

extra_css:
  - docs/mkdocs/assets/css/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: plantuml
          class: plantuml
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
      permalink: true
  - plantuml_markdown:
      server: !!python/object/apply:os.getenv
        - PLANTUML_SERVER_URL
        - http://www.plantuml.com/plantuml
      format: svg

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - docs/assets/js/extra.js

extra:
  plantuml_url: http://www.plantuml.com/plantuml
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/k2works/ai-programming-exercise
      name: GitHub Repository

plugins:
  - search

nav:
  - Home: index.md
  - 要件:
      - 概要: requirements/要件.md
      - ユーザーストーリー詳細: requirements/ユーザーストーリー詳細.md
      - ユースケース詳細: requirements/ユースケース詳細.md
      - 非機能要件: requirements/非機能要件.md
      - 運用要件とリリース計画: requirements/運用要件とリリース計画.md
  - 設計:
      - 概要: design/index.md
      - データモデル設計: design/データモデル設計.md
      - アーキテクチャ設計: design/アーキテクチャ設計.md
      - ドメインモデル設計: design/ドメインモデル設計.md
      - ユーザーインターフェース設計: design/ユーザーインターフェース設計.md
      - テスト戦略: design/テスト戦略.md
  - ADR:
    - 概要: adr/index.md
    - TypeScriptの採用: adr/0001-adopt-typescript.md
    - Vitestの採用: adr/0002-adopt-vitest.md
    - Canvas APIの採用: adr/0003-adopt-canvas-api.md
    - TDDアプローチの採用: adr/0004-adopt-tdd-approach.md
    - GitHub Actionsの採用: adr/0005-adopt-github-actions.md
    - Vercelの採用: adr/0006-adopt-vercel.md
