site_name: ゲーム開発のケーススタディ
site_description: Documentation for the Game Development project.
site_author: Project Team
repo_url: https://github.com/k2works/case-study-game-dev
repo_name: case-study-game-dev

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

extra_css:
  - docs/mkdocs/assets/css/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: plantuml
          class: plantuml
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
      permalink: true
  - plantuml_markdown:
      server: !!python/object/apply:os.getenv
        - PLANTUML_SERVER_URL
        - http://www.plantuml.com/plantuml
      format: svg

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - docs/assets/js/extra.js

extra:
  plantuml_url: http://www.plantuml.com/plantuml
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/k2works/ai-programming-exercise
      name: GitHub Repository

plugins:
  - search

nav:
  - Home: index.md
  - 要件:
      - 要件定義: requirements/要件定義.md
  - 開発:
    - アーキテクチャ: development/アーキテクチャ.md
    - 設計: development/設計.md
    - 実装: development/実装.md
  - 運用:
    - セットアップ: operation/セットアップ.md
    - Vercel設定: operation/Vercel設定.md
  - ADR:
    - "0001: TypeScriptの採用": adr/0001-adopt-typescript.md
    - "0002: Vitestの採用": adr/0002-adopt-vitest.md
    - "0003: DDDアーキテクチャの採用": adr/0003-adopt-ddd-architecture.md
    - "0004: Canvas APIの採用": adr/0004-adopt-canvas-api.md
    - "0005: Vercelデプロイの採用": adr/0005-adopt-vercel-deployment.md
  - 作業履歴:
    - 2025-07-31: journal/20250731.md
    - 2025-08-02: journal/20250802.md
