site_name: ゲーム開発のケーススタディ
site_description: Documentation for the Game Development project.
site_author: Project Team
repo_url: https://github.com/k2works/case-study-game-dev
repo_name: case-study-game-dev

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

extra_css:
  - docs/mkdocs/assets/css/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: plantuml
          class: plantuml
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
      permalink: true
  - plantuml_markdown:
      server: !!python/object/apply:os.getenv
        - PLANTUML_SERVER_URL
        - http://www.plantuml.com/plantuml
      format: svg

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - docs/assets/js/extra.js

extra:
  plantuml_url: http://www.plantuml.com/plantuml
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/k2works/ai-programming-exercise
      name: GitHub Repository

plugins:
  - search

nav:
  - Home: index.md
  - 要件:
    - 要件定義概要: requirements/index.md
    - リリース計画: requirements/リリース計画.md
    - 仕様: requirements/仕様.md
    - ユーザーストーリー: requirements/ユーザーストーリー.md
    - ユースケース: requirements/ユースケース.md
    - テスト戦略: requirements/テスト戦略.md
    - 非機能要件: requirements/非機能要件.md
    - 運用要件: requirements/運用要件.md
    - 技術スタック: requirements/技術スタック.md
  - 設計:
    - 設計概要: design/index.md
    - アーキテクチャ設計: design/アーキテクチャ設計.md
    - データモデル設計: design/データモデル設計.md
    - ドメインモデル設計: design/ドメインモデル設計.md
    - ユーザーインターフェース設計: design/ユーザーインターフェース設計.md
    - 実装戦略: design/実装戦略.md
  - 開発:
    - 開発概要: development/index.md
    - Phase 2レビュー: development/phase2-review.md
    - イテレーション1完了報告書: development/iteration1-completion-report.md
    - イテレーション1ふりかえり: development/iteration1-retrospective.md
  - 運用:
    - 運用概要: operation/index.md
    - セットアップ: operation/セットアップ.md
    - 環境構築: operation/環境構築.md
    - MkDocs GitHub Actions設定: operation/MkDocs_GitHub_Actions設定.md
  - ADR:
    - ADR一覧: adr/index.md
    - アーキテクチャ選定: adr/001-アーキテクチャ選定.md
    - フロントエンド技術スタック選定: adr/002-フロントエンド技術スタック選定.md
    - ドメイン駆動設計採用: adr/003-ドメイン駆動設計採用.md
    - TDD開発手法採用: adr/004-TDD開発手法採用.md
    - Vercelデプロイメント採用: adr/005-Vercelデプロイメント採用.md
    - 関数型プログラミング採用: adr/006-関数型プログラミング採用.md
    - テストライブラリ変更: adr/007-テストライブラリ変更.md
    - サイクロマティック複雑度制限: adr/008-サイクロマティック複雑度制限.md
    - dependency-cruiser採用: adr/009-dependency-cruiser採用.md
    - Codecov採用: adr/010-Codecov採用.md
