build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

style:
  MaxLineLength:
    maxLineLength: 120
  MagicNumber:
    active: false

complexity:
  ComplexMethod:
    threshold: 15
  TooManyFunctions:
    active: false
  LongMethod:
    threshold: 60

formatting:
  ParameterListWrapping:
    active: false
