<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="PredictionService.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MLWebApi.Domain\MLWebApi.Domain.fsproj" />
  </ItemGroup>

</Project>
