run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    enable:
      - shadow
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 10
  misspell:
    locale: US
  lll:
    line-length: 120
  gofmt:
    simplify: true
  goconst:
    min-len: 3
    min-occurrences: 2
  gosec:
    excludes:
      - G404  # Use of weak random number generator (OK for games)
      - G115  # Integer overflow conversion (OK in controlled contexts)

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - misspell
    - gofmt
    - gocyclo
    - goconst
    - gosec
    - unconvert
    - unused
    - staticcheck
    - typecheck
  disable:
    - errcheck
    - goimports

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - goconst
        - gocyclo
