name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: 'app/package-lock.json'
    
    - name: Install dependencies
      run: |
        cd app
        npm ci
    
    - name: Install Playwright Browsers
      run: |
        cd app
        npx playwright install --with-deps
    
    - name: Run unit tests first
      run: |
        cd app
        npm run test -- --run
    
    - name: Build application
      run: |
        cd app
        npm run build
    
    - name: Run Playwright tests
      run: |
        cd app
        npx playwright test
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: app/playwright-report/
        retention-days: 30
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: app/test-results/
        retention-days: 30